name: PostgreSQL service example
on: push

jobs:
  # Label of the container job
  container-job:
    # Containers must run in Linux based operating systems
    runs-on: ubuntu-latest
    # Docker Hub image that `container-job` executes in
    container: node:16-alpine3.14

    # Service containers to run with `container-job`
    services:
      # Label used to access the service container
      db:
        # Docker Hub image
        image: mysql
        ports:
          - '3306:3306'
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_USER: athenauser
          MYSQL_PASSWORD: password
          MYSQL_DATABASE: athena_test
        options: --health-cmd "mysqladmin ping" --health-interval 10s --health-timeout 5s --health-retries 10

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          cache: 'npm'
      - run: npm ci

      - name: Connect to PostgreSQL
        # Runs a script that creates a PostgreSQL table, populates
        # the table with data, and then retrieves the data.
        run: npm run test:ci
        # Environment variables used by the `client.js` script to create a new PostgreSQL table.
        env:
          # The hostname used to communicate with the PostgreSQL service container
          # The default PostgreSQL port
          ATHENA_DB_USER: athenauser
          ATHENA_DB_HOST: db
          ATHENA_DB_PORT: 3306
          ATHENA_DB_PASSWORD: password
